### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by ksolademi** [hirokiky/django-basicauth#1]
The decorator function to import is **@basic_auth_required**, not **@basic_auth_decorator**.

**Comment by hirokiky** [comment]
wow Thanks!

**Comment by hirokiky** [comment]
Solved. https://github.com/hirokiky/django-basicauth/commit/ba403dd3012a10ff1dcb19eba93ad9bf7488a74e
I added AUTHORS.txt to describe who hove contributed to this repo.
