### ISSUE TITLE
Add a Django middleware version

### ISSUE THREAD

**Issue by rbarrois** [hirokiky/django-basicauth#2]
Hi,

I'm interested in getting a middleware version of this feature; are you interesting in my contributing it?

If so, do you have any speicifc expectations on incoming pull requests?

Thanks!

**Comment by hirokiky** [comment]
Thank you! Just send PR. :+1:

**Comment by hirokiky** [comment]
@rbarrois Thanks for your great job. I released django-basicauth 0.2 
https://pypi.python.org/pypi/django-basicauth/0.2

Also I added your name on the AUTHORS.txt
https://github.com/hirokiky/django-basicauth/blob/master/AUTHORS.txt

**Comment by rbarrois** [comment]
@hirokiky Thanks :) Glad to have been helpful, and thanks for the nice library ;)
