### ISSUE TITLE
How to use django-basicauth with CBV?

### ISSUE THREAD

**Issue by guettli** [hirokiky/django-basicauth#5]
Hi,

could you please provide an example how to use django-basicauth with class-based-views?

I just want to have one CBV decorated. I would like to avoid a middleware.

Thank you

**Comment by aventurella** [comment]
```
from django.utils.decorators import method_decorator

@method_decorator(basic_auth_required, name='dispatch')
class YourView(TemplateView):
    template_name = "my-template.html"
```

See: https://docs.djangoproject.com/en/1.11/topics/class-based-views/intro/#decorating-the-class

**Comment by hirokiky** [comment]
Nice code @aventurella.

Or is there another way for CBV?
Like `LoginRequiredMixin` ?

**Comment by guettli** [comment]
Thank you very much. Can someone please update the README?

**Comment by hirokiky** [comment]
@guettli Alright.

**Comment by hirokiky** [comment]
OK, I wrote it. https://github.com/hirokiky/django-basicauth/commit/3404276ebca720016f87243dca1a968a3bbbff13
Really I appreciate.
